version: '2.1'

services:
  hdfs-name:
    image: biggis/hdfs:2.7.1
    ports:
      - "50070:50070"
      - "8020:8020"
    command: start.sh name
    environment:
      USER_ID: ${USER_ID-1000}
      USER_NAME: hdfs
      HADOOP_MASTER_ADDRESS: hdfs-name
      TIMEZONE: Europe/Berlin

  hdfs-sname:
    image: biggis/hdfs:2.7.1
    depends_on:
        - hdfs-name
    ports:
      - "50090:50090"
    command: start.sh sname
    environment:
      USER_ID: ${USER_ID-1000}
      USER_NAME: hdfs
      HADOOP_MASTER_ADDRESS: hdfs-name
      TIMEZONE: Europe/Berlin

  hdfs-data:
    image: biggis/hdfs:2.7.1
    depends_on:
        - hdfs-name
    ports:
      - "50010:50010"
      - "50075:50075"
    command: start.sh data
    environment:
      USER_ID: ${USER_ID-1000}
      USER_NAME: hdfs
      HADOOP_MASTER_ADDRESS: hdfs-name
      TIMEZONE: Europe/Berlin

  zookeeper:
    image: biggis/zookeeper:3.4.9
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      USER_ID: ${USER_ID-1000}
      USER_NAME: zookeeper
      TIMEZONE: Europe/Berlin

  accumulo-master:
    image: biggis/accumulo:1.7.3
    depends_on:
      - zookeeper
      - hdfs-name
    command: ["start.sh", "master", "--auto-init"]
    environment:
      USER_ID: ${USER_ID-1000}
      USER_NAME: accumulo
      HADOOP_MASTER_ADDRESS: hdfs-name
      ZOOKEEPERS: zookeeper
      ACCUMULO_PASSWORD: BigGISPwd
      TIMEZONE: Europe/Berlin

  accumulo-monitor:
    image: biggis/accumulo:1.7.3
    depends_on:
      - zookeeper
      - accumulo-master
    command: ["start.sh", "monitor"]
    ports:
      - 50095:50095
    environment:
      USER_ID: ${USER_ID-1000}
      USER_NAME: accumulo
      HADOOP_MASTER_ADDRESS: hdfs-name
      ZOOKEEPERS: zookeeper
      TIMEZONE: Europe/Berlin

  accumulo-tserver:
    image: biggis/accumulo:1.7.3
    depends_on:
      - zookeeper
      - accumulo-master
    command: ["start.sh", "tserver"]
    environment:
      USER_ID: ${USER_ID-1000}
      USER_NAME: accumulo
      HADOOP_MASTER_ADDRESS: hdfs-name
      ZOOKEEPERS: zookeeper
      TIMEZONE: Europe/Berlin
